<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <InvariantGlobalization>true</InvariantGlobalization>
        <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
        <AccelerateBuildsInVisualStudio>false</AccelerateBuildsInVisualStudio>
    </PropertyGroup>

    <ItemGroup>
        <EmbeddedResource Update="Resources\Strings.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Strings.Designer.cs</LastGenOutput>
        </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.7" />
        <PackageReference Include="Microsoft.Extensions.Localization" Version="10.0.6" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\HomeBook.Frontend.Core\HomeBook.Frontend.Core.csproj"/>
        <ProjectReference Include="..\HomeBook.Frontend.Modules.Abstractions\HomeBook.Frontend.Modules.Abstractions.csproj"/>
        <ProjectReference Include="..\HomeBook.Frontend.UI\HomeBook.Frontend.UI.csproj"/>
    </ItemGroup>

</Project>
