// <auto-generated/>
#pragma warning disable CS0618
using HomeBook.Client.User.Preferences.Locale;
using HomeBook.Client.User.Preferences.Wallpaper;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace HomeBook.Client.User.Preferences
{
    /// <summary>
    /// Builds and executes requests for operations under \user\preferences
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PreferencesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The locale property</summary>
        public global::HomeBook.Client.User.Preferences.Locale.LocaleRequestBuilder Locale
        {
            get => new global::HomeBook.Client.User.Preferences.Locale.LocaleRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The wallpaper property</summary>
        public global::HomeBook.Client.User.Preferences.Wallpaper.WallpaperRequestBuilder Wallpaper
        {
            get => new global::HomeBook.Client.User.Preferences.Wallpaper.WallpaperRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::HomeBook.Client.User.Preferences.PreferencesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PreferencesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user/preferences", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::HomeBook.Client.User.Preferences.PreferencesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PreferencesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user/preferences", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
