// <auto-generated/>
#pragma warning disable CS0618
using HomeBook.Client.Modules.Homebook.Finances.Calculations.Savings;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace HomeBook.Client.Modules.Homebook.Finances.Calculations
{
    /// <summary>
    /// Builds and executes requests for operations under \modules\homebook\finances\calculations
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CalculationsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The savings property</summary>
        public global::HomeBook.Client.Modules.Homebook.Finances.Calculations.Savings.SavingsRequestBuilder Savings
        {
            get => new global::HomeBook.Client.Modules.Homebook.Finances.Calculations.Savings.SavingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::HomeBook.Client.Modules.Homebook.Finances.Calculations.CalculationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CalculationsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/modules/homebook/finances/calculations", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::HomeBook.Client.Modules.Homebook.Finances.Calculations.CalculationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CalculationsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/modules/homebook/finances/calculations", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
