//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeBook.Frontend.Module.Kitchen.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("HomeBook.Frontend.Module.Kitchen.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ModuleName {
            get {
                return ResourceManager.GetString("ModuleName", resourceCulture);
            }
        }
        
        public static string ModuleDescription {
            get {
                return ResourceManager.GetString("ModuleDescription", resourceCulture);
            }
        }
        
        public static string StartMenuItem_Recipes_Title {
            get {
                return ResourceManager.GetString("StartMenuItem_Recipes_Title", resourceCulture);
            }
        }
        
        public static string StartMenuItem_Pantry_Title {
            get {
                return ResourceManager.GetString("StartMenuItem_Pantry_Title", resourceCulture);
            }
        }
        
        public static string StartMenuItem_Recipes_Caption {
            get {
                return ResourceManager.GetString("StartMenuItem_Recipes_Caption", resourceCulture);
            }
        }
        
        public static string StartMenuItem_Pantry_Caption {
            get {
                return ResourceManager.GetString("StartMenuItem_Pantry_Caption", resourceCulture);
            }
        }
        
        public static string StartMenuItem_MealPlan_Title {
            get {
                return ResourceManager.GetString("StartMenuItem_MealPlan_Title", resourceCulture);
            }
        }
        
        public static string StartMenuItem_MealPlan_Caption {
            get {
                return ResourceManager.GetString("StartMenuItem_MealPlan_Caption", resourceCulture);
            }
        }
        
        public static string DateTimeFormat_ShortDateOnlyFormat {
            get {
                return ResourceManager.GetString("DateTimeFormat_ShortDateOnlyFormat", resourceCulture);
            }
        }
        
        public static string PlanOverview_Header_CalendarWeek_TextTemplate {
            get {
                return ResourceManager.GetString("PlanOverview_Header_CalendarWeek_TextTemplate", resourceCulture);
            }
        }
        
        public static string PlanOverview_MealType_Breakfast_Text {
            get {
                return ResourceManager.GetString("PlanOverview_MealType_Breakfast_Text", resourceCulture);
            }
        }
        
        public static string PlanOverview_MealType_Lunch_Text {
            get {
                return ResourceManager.GetString("PlanOverview_MealType_Lunch_Text", resourceCulture);
            }
        }
        
        public static string PlanOverview_MealType_Dinner_Text {
            get {
                return ResourceManager.GetString("PlanOverview_MealType_Dinner_Text", resourceCulture);
            }
        }
        
        public static string RecipeOverview_AnnotationServings_TextTemplate {
            get {
                return ResourceManager.GetString("RecipeOverview_AnnotationServings_TextTemplate", resourceCulture);
            }
        }
        
        public static string RecipeEdit_RecipeNameEditToolTip_Text {
            get {
                return ResourceManager.GetString("RecipeEdit_RecipeNameEditToolTip_Text", resourceCulture);
            }
        }
        
        public static string RecipeEdit_RecipeNameEditTextField_Placeholder {
            get {
                return ResourceManager.GetString("RecipeEdit_RecipeNameEditTextField_Placeholder", resourceCulture);
            }
        }
        
        public static string RecipeEdit_ViewRecipeButton_Text {
            get {
                return ResourceManager.GetString("RecipeEdit_ViewRecipeButton_Text", resourceCulture);
            }
        }
        
        public static string RecipeEdit_RecipeNameSaveTooltip_Text {
            get {
                return ResourceManager.GetString("RecipeEdit_RecipeNameSaveTooltip_Text", resourceCulture);
            }
        }
        
        public static string RecipeEdit_RecipeDeleteTooltip_Text {
            get {
                return ResourceManager.GetString("RecipeEdit_RecipeDeleteTooltip_Text", resourceCulture);
            }
        }
        
        public static string RecipeEdit_RecipeDescriptionTextField_Label {
            get {
                return ResourceManager.GetString("RecipeEdit_RecipeDescriptionTextField_Label", resourceCulture);
            }
        }
        
        public static string RecipeEdit_ServingsLabel_Singular {
            get {
                return ResourceManager.GetString("RecipeEdit_ServingsLabel_Singular", resourceCulture);
            }
        }
        
        public static string RecipeEdit_ServingsLabel_Plural {
            get {
                return ResourceManager.GetString("RecipeEdit_ServingsLabel_Plural", resourceCulture);
            }
        }
        
        public static string RecipeEdit_DurationAdditionalArea_Title {
            get {
                return ResourceManager.GetString("RecipeEdit_DurationAdditionalArea_Title", resourceCulture);
            }
        }
        
        public static string RecipeEdit_AbortButton_Content {
            get {
                return ResourceManager.GetString("RecipeEdit_AbortButton_Content", resourceCulture);
            }
        }
        
        public static string RecipeEdit_SaveRecipeButton_Content {
            get {
                return ResourceManager.GetString("RecipeEdit_SaveRecipeButton_Content", resourceCulture);
            }
        }
        
        public static string RecipeEdit_RecipeSource_Content {
            get {
                return ResourceManager.GetString("RecipeEdit_RecipeSource_Content", resourceCulture);
            }
        }
        
        public static string RecipeEdit_RecipeComment_Content {
            get {
                return ResourceManager.GetString("RecipeEdit_RecipeComment_Content", resourceCulture);
            }
        }
        
        public static string RecipeEdit_CaloriesPerServing_Content {
            get {
                return ResourceManager.GetString("RecipeEdit_CaloriesPerServing_Content", resourceCulture);
            }
        }
        
        public static string RecipeEdit_RestingTime_Content {
            get {
                return ResourceManager.GetString("RecipeEdit_RestingTime_Content", resourceCulture);
            }
        }
        
        public static string RecipeEdit_CookingBakingTime_Content {
            get {
                return ResourceManager.GetString("RecipeEdit_CookingBakingTime_Content", resourceCulture);
            }
        }
        
        public static string RecipeEdit_WorkingTime_Content {
            get {
                return ResourceManager.GetString("RecipeEdit_WorkingTime_Content", resourceCulture);
            }
        }
        
        public static string RecipeEdit_WorkingTimeHour_AdornmentText {
            get {
                return ResourceManager.GetString("RecipeEdit_WorkingTimeHour_AdornmentText", resourceCulture);
            }
        }
        
        public static string RecipeEdit_WorkingTimeMinute_AdornmentText {
            get {
                return ResourceManager.GetString("RecipeEdit_WorkingTimeMinute_AdornmentText", resourceCulture);
            }
        }
        
        public static string RecipeEdit_CookingBakingTimeHour_AdornmentText {
            get {
                return ResourceManager.GetString("RecipeEdit_CookingBakingTimeHour_AdornmentText", resourceCulture);
            }
        }
        
        public static string RecipeEdit_CookingBakingTimeMinute_AdornmentText {
            get {
                return ResourceManager.GetString("RecipeEdit_CookingBakingTimeMinute_AdornmentText", resourceCulture);
            }
        }
        
        public static string RecipeEdit_RestingTimeHour_AdornmentText {
            get {
                return ResourceManager.GetString("RecipeEdit_RestingTimeHour_AdornmentText", resourceCulture);
            }
        }
        
        public static string RecipeEdit_RestingTimeMinute_AdornmentText {
            get {
                return ResourceManager.GetString("RecipeEdit_RestingTimeMinute_AdornmentText", resourceCulture);
            }
        }
        
        public static string RecipeEdit_CaloriesPerServing_AdornmentText {
            get {
                return ResourceManager.GetString("RecipeEdit_CaloriesPerServing_AdornmentText", resourceCulture);
            }
        }
        
        public static string RecipeEditIngredients_Ingredients_Title {
            get {
                return ResourceManager.GetString("RecipeEditIngredients_Ingredients_Title", resourceCulture);
            }
        }
        
        public static string RecipeEditIngredients_Quantity_Placeholder {
            get {
                return ResourceManager.GetString("RecipeEditIngredients_Quantity_Placeholder", resourceCulture);
            }
        }
        
        public static string RecipeEditIngredients_Unit_Placeholder {
            get {
                return ResourceManager.GetString("RecipeEditIngredients_Unit_Placeholder", resourceCulture);
            }
        }
        
        public static string RecipeEditIngredients_IngredientName_Placeholder {
            get {
                return ResourceManager.GetString("RecipeEditIngredients_IngredientName_Placeholder", resourceCulture);
            }
        }
        
        public static string RecipeEditIngredients_AdditionalNote_Placeholder {
            get {
                return ResourceManager.GetString("RecipeEditIngredients_AdditionalNote_Placeholder", resourceCulture);
            }
        }
        
        public static string RecipeEditSteps_Steps_Title {
            get {
                return ResourceManager.GetString("RecipeEditSteps_Steps_Title", resourceCulture);
            }
        }
        
        public static string RecipeEditSteps_StepIndexText_Content {
            get {
                return ResourceManager.GetString("RecipeEditSteps_StepIndexText_Content", resourceCulture);
            }
        }
        
        public static string RecipeEditSteps_StepTimerText_Content {
            get {
                return ResourceManager.GetString("RecipeEditSteps_StepTimerText_Content", resourceCulture);
            }
        }
        
        public static string RecipeEditSteps_StepTimerTitle_Content {
            get {
                return ResourceManager.GetString("RecipeEditSteps_StepTimerTitle_Content", resourceCulture);
            }
        }
        
        public static string RecipeEditSteps_StepTimerHour_AdornmentText {
            get {
                return ResourceManager.GetString("RecipeEditSteps_StepTimerHour_AdornmentText", resourceCulture);
            }
        }
        
        public static string RecipeEditSteps_StepTimerMinute_AdornmentText {
            get {
                return ResourceManager.GetString("RecipeEditSteps_StepTimerMinute_AdornmentText", resourceCulture);
            }
        }
        
        public static string RecipeEditSteps_StepDescription_Placeholder {
            get {
                return ResourceManager.GetString("RecipeEditSteps_StepDescription_Placeholder", resourceCulture);
            }
        }
    }
}
