<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <NeutralLanguage>en-US</NeutralLanguage>
        <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
        <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.5" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="10.0.5" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.5" PrivateAssets="all" />
        <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.5" />
        <PackageReference Include="Microsoft.AspNetCore.Localization" Version="2.3.9" />
        <PackageReference Include="Microsoft.FeatureManagement" Version="4.4.0" />
        <PackageReference Include="MudBlazor" Version="9.1.0" />
    </ItemGroup>

    <Target Name="CompileSass" BeforeTargets="Build">
        <Exec Command="npx sass Styles/app.scss wwwroot/css/app.css --style=expanded --source-map"/>
        <Exec Command="npx sass Styles/app.scss wwwroot/css/app.min.css --style=compressed --source-map"/>
    </Target>

    <ItemGroup>
        <Content Update="wwwroot\appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Update="wwwroot\appsettings.Development.json">
            <DependentUpon>appsettings.json</DependentUpon>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\HomeBook.Frontend.Core\HomeBook.Frontend.Core.csproj"/>
        <ProjectReference Include="..\HomeBook.Frontend.Module.Finances\HomeBook.Frontend.Module.Finances.csproj"/>
        <ProjectReference Include="..\HomeBook.Frontend.Module.Kitchen\HomeBook.Frontend.Module.Kitchen.csproj"/>
        <ProjectReference Include="..\HomeBook.Frontend.Module.PlatformInfo\HomeBook.Frontend.Module.PlatformInfo.csproj"/>
        <ProjectReference Include="..\HomeBook.Frontend.Services\HomeBook.Frontend.Services.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Properties\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>LocalizationStrings.resx</DependentUpon>
        </Compile>
    </ItemGroup>

</Project>
