// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace HomeBook.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetSystemStorageInfoResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The cache property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::HomeBook.Client.Models.StorageUsageResponse? Cache { get; set; }
#nullable restore
#else
        public global::HomeBook.Client.Models.StorageUsageResponse Cache { get; set; }
#endif
        /// <summary>The logs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::HomeBook.Client.Models.StorageUsageResponse? Logs { get; set; }
#nullable restore
#else
        public global::HomeBook.Client.Models.StorageUsageResponse Logs { get; set; }
#endif
        /// <summary>The mediaStorage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::HomeBook.Client.Models.MediaStorageSizeTypeResponse>? MediaStorage { get; set; }
#nullable restore
#else
        public List<global::HomeBook.Client.Models.MediaStorageSizeTypeResponse> MediaStorage { get; set; }
#endif
        /// <summary>The temp property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::HomeBook.Client.Models.StorageUsageResponse? Temp { get; set; }
#nullable restore
#else
        public global::HomeBook.Client.Models.StorageUsageResponse Temp { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::HomeBook.Client.Models.GetSystemStorageInfoResponse"/> and sets the default values.
        /// </summary>
        public GetSystemStorageInfoResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::HomeBook.Client.Models.GetSystemStorageInfoResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::HomeBook.Client.Models.GetSystemStorageInfoResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::HomeBook.Client.Models.GetSystemStorageInfoResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cache", n => { Cache = n.GetObjectValue<global::HomeBook.Client.Models.StorageUsageResponse>(global::HomeBook.Client.Models.StorageUsageResponse.CreateFromDiscriminatorValue); } },
                { "logs", n => { Logs = n.GetObjectValue<global::HomeBook.Client.Models.StorageUsageResponse>(global::HomeBook.Client.Models.StorageUsageResponse.CreateFromDiscriminatorValue); } },
                { "mediaStorage", n => { MediaStorage = n.GetCollectionOfObjectValues<global::HomeBook.Client.Models.MediaStorageSizeTypeResponse>(global::HomeBook.Client.Models.MediaStorageSizeTypeResponse.CreateFromDiscriminatorValue)?.AsList(); } },
                { "temp", n => { Temp = n.GetObjectValue<global::HomeBook.Client.Models.StorageUsageResponse>(global::HomeBook.Client.Models.StorageUsageResponse.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::HomeBook.Client.Models.StorageUsageResponse>("cache", Cache);
            writer.WriteObjectValue<global::HomeBook.Client.Models.StorageUsageResponse>("logs", Logs);
            writer.WriteCollectionOfObjectValues<global::HomeBook.Client.Models.MediaStorageSizeTypeResponse>("mediaStorage", MediaStorage);
            writer.WriteObjectValue<global::HomeBook.Client.Models.StorageUsageResponse>("temp", Temp);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
