// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace HomeBook.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RecipeDetailResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The caloriesKcal property</summary>
        public int? CaloriesKcal { get; set; }
        /// <summary>The comments property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Comments { get; set; }
#nullable restore
#else
        public string Comments { get; set; }
#endif
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The durationCookingMinutes property</summary>
        public int? DurationCookingMinutes { get; set; }
        /// <summary>The durationRestingMinutes property</summary>
        public int? DurationRestingMinutes { get; set; }
        /// <summary>The durationWorkingMinutes property</summary>
        public int? DurationWorkingMinutes { get; set; }
        /// <summary>The id property</summary>
        public Guid? Id { get; set; }
        /// <summary>The ingredients property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::HomeBook.Client.Models.RecipeIngredientResponse>? Ingredients { get; set; }
#nullable restore
#else
        public List<global::HomeBook.Client.Models.RecipeIngredientResponse> Ingredients { get; set; }
#endif
        /// <summary>The mediaIds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Guid?>? MediaIds { get; set; }
#nullable restore
#else
        public List<Guid?> MediaIds { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The normalizedName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NormalizedName { get; set; }
#nullable restore
#else
        public string NormalizedName { get; set; }
#endif
        /// <summary>The servings property</summary>
        public int? Servings { get; set; }
        /// <summary>The source property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Source { get; set; }
#nullable restore
#else
        public string Source { get; set; }
#endif
        /// <summary>The steps property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::HomeBook.Client.Models.RecipeStepResponse>? Steps { get; set; }
#nullable restore
#else
        public List<global::HomeBook.Client.Models.RecipeStepResponse> Steps { get; set; }
#endif
        /// <summary>The username property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Username { get; set; }
#nullable restore
#else
        public string Username { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::HomeBook.Client.Models.RecipeDetailResponse"/> and sets the default values.
        /// </summary>
        public RecipeDetailResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::HomeBook.Client.Models.RecipeDetailResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::HomeBook.Client.Models.RecipeDetailResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::HomeBook.Client.Models.RecipeDetailResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "caloriesKcal", n => { CaloriesKcal = n.GetIntValue(); } },
                { "comments", n => { Comments = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "durationCookingMinutes", n => { DurationCookingMinutes = n.GetIntValue(); } },
                { "durationRestingMinutes", n => { DurationRestingMinutes = n.GetIntValue(); } },
                { "durationWorkingMinutes", n => { DurationWorkingMinutes = n.GetIntValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "ingredients", n => { Ingredients = n.GetCollectionOfObjectValues<global::HomeBook.Client.Models.RecipeIngredientResponse>(global::HomeBook.Client.Models.RecipeIngredientResponse.CreateFromDiscriminatorValue)?.AsList(); } },
                { "mediaIds", n => { MediaIds = n.GetCollectionOfPrimitiveValues<Guid?>()?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "normalizedName", n => { NormalizedName = n.GetStringValue(); } },
                { "servings", n => { Servings = n.GetIntValue(); } },
                { "source", n => { Source = n.GetStringValue(); } },
                { "steps", n => { Steps = n.GetCollectionOfObjectValues<global::HomeBook.Client.Models.RecipeStepResponse>(global::HomeBook.Client.Models.RecipeStepResponse.CreateFromDiscriminatorValue)?.AsList(); } },
                { "username", n => { Username = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("caloriesKcal", CaloriesKcal);
            writer.WriteStringValue("comments", Comments);
            writer.WriteStringValue("description", Description);
            writer.WriteIntValue("durationCookingMinutes", DurationCookingMinutes);
            writer.WriteIntValue("durationRestingMinutes", DurationRestingMinutes);
            writer.WriteIntValue("durationWorkingMinutes", DurationWorkingMinutes);
            writer.WriteGuidValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::HomeBook.Client.Models.RecipeIngredientResponse>("ingredients", Ingredients);
            writer.WriteCollectionOfPrimitiveValues<Guid?>("mediaIds", MediaIds);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("normalizedName", NormalizedName);
            writer.WriteIntValue("servings", Servings);
            writer.WriteStringValue("source", Source);
            writer.WriteCollectionOfObjectValues<global::HomeBook.Client.Models.RecipeStepResponse>("steps", Steps);
            writer.WriteStringValue("username", Username);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
