// <auto-generated/>
#pragma warning disable CS0618
using HomeBook.Client.Models;
using HomeBook.Client.Modules.Homebook.Kitchen.Recipes.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace HomeBook.Client.Modules.Homebook.Kitchen.Recipes
{
    /// <summary>
    /// Builds and executes requests for operations under \modules\homebook\kitchen\recipes
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RecipesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the HomeBook.Client.modules.homebook.kitchen.recipes.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::HomeBook.Client.Modules.Homebook.Kitchen.Recipes.Item.RecipesItemRequestBuilder"/></returns>
        public global::HomeBook.Client.Modules.Homebook.Kitchen.Recipes.Item.RecipesItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::HomeBook.Client.Modules.Homebook.Kitchen.Recipes.Item.RecipesItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the HomeBook.Client.modules.homebook.kitchen.recipes.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::HomeBook.Client.Modules.Homebook.Kitchen.Recipes.Item.RecipesItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::HomeBook.Client.Modules.Homebook.Kitchen.Recipes.Item.RecipesItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("id", position);
                return new global::HomeBook.Client.Modules.Homebook.Kitchen.Recipes.Item.RecipesItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::HomeBook.Client.Modules.Homebook.Kitchen.Recipes.RecipesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RecipesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/modules/homebook/kitchen/recipes?searchFilter={searchFilter}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::HomeBook.Client.Modules.Homebook.Kitchen.Recipes.RecipesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RecipesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/modules/homebook/kitchen/recipes?searchFilter={searchFilter}", rawUrl)
        {
        }
        /// <summary>
        /// returns recipes matching the search filterHTTP 200: Recipes were foundHTTP 401: User is not authorizedHTTP 500: Unknown error while getting recipes
        /// </summary>
        /// <returns>A <see cref="global::HomeBook.Client.Models.RecipesListResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::HomeBook.Client.Models.RecipesListResponse?> GetAsync(Action<RequestConfiguration<global::HomeBook.Client.Modules.Homebook.Kitchen.Recipes.RecipesRequestBuilder.RecipesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::HomeBook.Client.Models.RecipesListResponse> GetAsync(Action<RequestConfiguration<global::HomeBook.Client.Modules.Homebook.Kitchen.Recipes.RecipesRequestBuilder.RecipesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::HomeBook.Client.Models.RecipesListResponse>(requestInfo, global::HomeBook.Client.Models.RecipesListResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// creates a new recipeHTTP 201: Recipe was createdHTTP 400: Invalid request dataHTTP 401: User is not authorizedHTTP 500: Unknown error while creating recipe
        /// </summary>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task PostAsync(global::HomeBook.Client.Models.RecipeRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task PostAsync(global::HomeBook.Client.Models.RecipeRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            await RequestAdapter.SendNoContentAsync(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// returns recipes matching the search filterHTTP 200: Recipes were foundHTTP 401: User is not authorizedHTTP 500: Unknown error while getting recipes
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::HomeBook.Client.Modules.Homebook.Kitchen.Recipes.RecipesRequestBuilder.RecipesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::HomeBook.Client.Modules.Homebook.Kitchen.Recipes.RecipesRequestBuilder.RecipesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// creates a new recipeHTTP 201: Recipe was createdHTTP 400: Invalid request dataHTTP 401: User is not authorizedHTTP 500: Unknown error while creating recipe
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::HomeBook.Client.Models.RecipeRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::HomeBook.Client.Models.RecipeRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, "{+baseurl}/modules/homebook/kitchen/recipes", PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::HomeBook.Client.Modules.Homebook.Kitchen.Recipes.RecipesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::HomeBook.Client.Modules.Homebook.Kitchen.Recipes.RecipesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::HomeBook.Client.Modules.Homebook.Kitchen.Recipes.RecipesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// returns recipes matching the search filterHTTP 200: Recipes were foundHTTP 401: User is not authorizedHTTP 500: Unknown error while getting recipes
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RecipesRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("searchFilter")]
            public string? SearchFilter { get; set; }
#nullable restore
#else
            [QueryParameter("searchFilter")]
            public string SearchFilter { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RecipesRequestBuilderGetRequestConfiguration : RequestConfiguration<global::HomeBook.Client.Modules.Homebook.Kitchen.Recipes.RecipesRequestBuilder.RecipesRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class RecipesRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
