// <auto-generated/>
#pragma warning disable CS0618
using HomeBook.Client.Modules.Homebook.Finances;
using HomeBook.Client.Modules.Homebook.Kitchen;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace HomeBook.Client.Modules.Homebook
{
    /// <summary>
    /// Builds and executes requests for operations under \modules\homebook
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class HomebookRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The finances property</summary>
        public global::HomeBook.Client.Modules.Homebook.Finances.FinancesRequestBuilder Finances
        {
            get => new global::HomeBook.Client.Modules.Homebook.Finances.FinancesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The kitchen property</summary>
        public global::HomeBook.Client.Modules.Homebook.Kitchen.KitchenRequestBuilder Kitchen
        {
            get => new global::HomeBook.Client.Modules.Homebook.Kitchen.KitchenRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::HomeBook.Client.Modules.Homebook.HomebookRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public HomebookRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/modules/homebook", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::HomeBook.Client.Modules.Homebook.HomebookRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public HomebookRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/modules/homebook", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
