// <auto-generated/>
#pragma warning disable CS0618
using HomeBook.Client.Account;
using HomeBook.Client.FileNamespace;
using HomeBook.Client.Info;
using HomeBook.Client.Modules;
using HomeBook.Client.Platform;
using HomeBook.Client.Search;
using HomeBook.Client.Setup;
using HomeBook.Client.System;
using HomeBook.Client.Update;
using HomeBook.Client.User;
using HomeBook.Client.VersionNamespace;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace HomeBook.Client
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BackendClient : BaseRequestBuilder
    {
        /// <summary>The account property</summary>
        public global::HomeBook.Client.Account.AccountRequestBuilder Account
        {
            get => new global::HomeBook.Client.Account.AccountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The file property</summary>
        public global::HomeBook.Client.FileNamespace.FileRequestBuilder File
        {
            get => new global::HomeBook.Client.FileNamespace.FileRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The info property</summary>
        public global::HomeBook.Client.Info.InfoRequestBuilder Info
        {
            get => new global::HomeBook.Client.Info.InfoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The modules property</summary>
        public global::HomeBook.Client.Modules.ModulesRequestBuilder Modules
        {
            get => new global::HomeBook.Client.Modules.ModulesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The platform property</summary>
        public global::HomeBook.Client.Platform.PlatformRequestBuilder Platform
        {
            get => new global::HomeBook.Client.Platform.PlatformRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The search property</summary>
        public global::HomeBook.Client.Search.SearchRequestBuilder Search
        {
            get => new global::HomeBook.Client.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The setup property</summary>
        public global::HomeBook.Client.Setup.SetupRequestBuilder Setup
        {
            get => new global::HomeBook.Client.Setup.SetupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The system property</summary>
        public global::HomeBook.Client.System.SystemRequestBuilder System
        {
            get => new global::HomeBook.Client.System.SystemRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The update property</summary>
        public global::HomeBook.Client.Update.UpdateRequestBuilder Update
        {
            get => new global::HomeBook.Client.Update.UpdateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The user property</summary>
        public global::HomeBook.Client.User.UserRequestBuilder User
        {
            get => new global::HomeBook.Client.User.UserRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The version property</summary>
        public global::HomeBook.Client.VersionNamespace.VersionRequestBuilder Version
        {
            get => new global::HomeBook.Client.VersionNamespace.VersionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::HomeBook.Client.BackendClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BackendClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
        }
    }
}
#pragma warning restore CS0618
