<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <OpenApiDocumentsDirectory>.</OpenApiDocumentsDirectory>
    </PropertyGroup>

    <!-- Define MACOS symbol when running on macOS -->
    <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('OSX'))">
        <DefineConstants>$(DefineConstants);MACOS</DefineConstants>
    </PropertyGroup>

    <!-- Make internal methods visible to test projects -->
    <ItemGroup>
        <InternalsVisibleTo Include="HomeBook.UnitTests"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
        <PackageReference Include="Microsoft.Extensions.ApiDescription.Server" Version="10.0.5">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Scalar.AspNetCore" Version="2.13.21" />
        <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1"/>
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <Content Update="appsettings.Development.json">
            <DependentUpon>appsettings.json</DependentUpon>
        </Content>
        <Content Update="appsettings.Docker.json">
            <DependentUpon>appsettings.json</DependentUpon>
        </Content>
        <Content Update="appsettings.Production.json">
            <DependentUpon>appsettings.json</DependentUpon>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\HomeBook.Backend.Abstractions\HomeBook.Backend.Abstractions.csproj"/>
        <ProjectReference Include="..\HomeBook.Backend.Core.Search\HomeBook.Backend.Core.Search.csproj"/>
        <ProjectReference Include="..\HomeBook.Backend.Core.Storage\HomeBook.Backend.Core.Storage.csproj" />
        <ProjectReference Include="..\HomeBook.Backend.Core\HomeBook.Backend.Core.csproj"/>
        <ProjectReference Include="..\HomeBook.Backend.Core.Account\HomeBook.Backend.Core.Account.csproj"/>
        <ProjectReference Include="..\HomeBook.Backend.Data.Mysql\HomeBook.Backend.Data.Mysql.csproj"/>
        <ProjectReference Include="..\HomeBook.Backend.Data.PostgreSql\HomeBook.Backend.Data.PostgreSql.csproj"/>
        <ProjectReference Include="..\HomeBook.Backend.Data.Sqlite\HomeBook.Backend.Data.Sqlite.csproj"/>
        <ProjectReference Include="..\HomeBook.Backend.DTOs\HomeBook.Backend.DTOs.csproj"/>
        <ProjectReference Include="..\HomeBook.Backend.Core.Account\HomeBook.Backend.Core.Account.csproj"/>
        <ProjectReference Include="..\HomeBook.Backend.Core.DataProvider\HomeBook.Backend.Core.DataProvider.csproj"/>
        <ProjectReference Include="..\HomeBook.Backend.Core.Licenses\HomeBook.Backend.Core.Licenses.csproj"/>
        <ProjectReference Include="..\Homebook.Backend.Core.Setup\Homebook.Backend.Core.Setup.csproj"/>
        <ProjectReference Include="..\HomeBook.Backend.Module.Finances\HomeBook.Backend.Module.Finances.csproj"/>
        <ProjectReference Include="..\HomeBook.Backend.Module.Kitchen\HomeBook.Backend.Module.Kitchen.csproj"/>
        <ProjectReference Include="..\HomeBook.Backend.Modules.Abstractions\HomeBook.Backend.Modules.Abstractions.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="env\**\*.*">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

</Project>
