// <auto-generated/>
#pragma warning disable CS0618
using HomeBook.Client.Modules.Homebook.Finances.Calculations;
using HomeBook.Client.Modules.Homebook.Finances.SavingGoals;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace HomeBook.Client.Modules.Homebook.Finances
{
    /// <summary>
    /// Builds and executes requests for operations under \modules\homebook\finances
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FinancesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The calculations property</summary>
        public global::HomeBook.Client.Modules.Homebook.Finances.Calculations.CalculationsRequestBuilder Calculations
        {
            get => new global::HomeBook.Client.Modules.Homebook.Finances.Calculations.CalculationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The savingGoals property</summary>
        public global::HomeBook.Client.Modules.Homebook.Finances.SavingGoals.SavingGoalsRequestBuilder SavingGoals
        {
            get => new global::HomeBook.Client.Modules.Homebook.Finances.SavingGoals.SavingGoalsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::HomeBook.Client.Modules.Homebook.Finances.FinancesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FinancesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/modules/homebook/finances", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::HomeBook.Client.Modules.Homebook.Finances.FinancesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FinancesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/modules/homebook/finances", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
