// <auto-generated/>
#pragma warning disable CS0618
using HomeBook.Client.System.Instance;
using HomeBook.Client.System.Storage;
using HomeBook.Client.System.Users;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace HomeBook.Client.System
{
    /// <summary>
    /// Builds and executes requests for operations under \system
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SystemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The instance property</summary>
        public global::HomeBook.Client.System.Instance.InstanceRequestBuilder Instance
        {
            get => new global::HomeBook.Client.System.Instance.InstanceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The storage property</summary>
        public global::HomeBook.Client.System.Storage.StorageRequestBuilder Storage
        {
            get => new global::HomeBook.Client.System.Storage.StorageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::HomeBook.Client.System.Users.UsersRequestBuilder Users
        {
            get => new global::HomeBook.Client.System.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::HomeBook.Client.System.SystemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SystemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/system", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::HomeBook.Client.System.SystemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SystemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/system", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
