// <auto-generated/>
#pragma warning disable CS0618
using HomeBook.Client.Storage.Files;
using HomeBook.Client.Storage.Scopes;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace HomeBook.Client.Storage
{
    /// <summary>
    /// Builds and executes requests for operations under \storage
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StorageRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The files property</summary>
        public global::HomeBook.Client.Storage.Files.FilesRequestBuilder Files
        {
            get => new global::HomeBook.Client.Storage.Files.FilesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The scopes property</summary>
        public global::HomeBook.Client.Storage.Scopes.ScopesRequestBuilder Scopes
        {
            get => new global::HomeBook.Client.Storage.Scopes.ScopesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::HomeBook.Client.Storage.StorageRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StorageRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/storage", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::HomeBook.Client.Storage.StorageRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StorageRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/storage", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
