<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.5" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.5" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.5" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.5" />
      <PackageReference Include="Microsoft.JSInterop" Version="10.0.5" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\HomeBook.Client\HomeBook.Client.csproj" />
      <ProjectReference Include="..\HomeBook.Frontend.Abstractions\HomeBook.Frontend.Abstractions.csproj" />
      <ProjectReference Include="..\HomeBook.Frontend.Core\HomeBook.Frontend.Core.csproj" />
      <ProjectReference Include="..\HomeBook.Frontend.UI\HomeBook.Frontend.UI.csproj" />
    </ItemGroup>

</Project>
