name: Build and Deploy

on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: write
    packages: write

env:
    DOCKER_IMAGE: "docker.io/homebookapp/app"
    DOCKER_PLATFORMS: "linux/amd64,linux/arm64"
    VERSION: "1.0.${{ github.run_number }}"
    DOTNET_VERSION: "10.0.101"
    SOLUTION_FILE: "./homebook.slnx"
    BACKEND_CSPROJ: "./source/HomeBook.Backend/HomeBook.Backend.csproj"
    FRONTEND_CSPROJ: "./source/HomeBook.Frontend/HomeBook.Frontend.csproj"
    FRONTEND_APPSETTINGS_FILE: "./source/HomeBook.Frontend/wwwroot/appsettings.json"
    BACKEND_APPSETTINGS_FILE: "./source/HomeBook.Backend/appsettings.json"
    OPENAPI_FILE: "./source/HomeBook.Backend/HomeBook.Backend.json"
    CLIENT_CSPROJ: "./source/HomeBook.Client/HomeBook.Client.csproj"
    CLIENT_OUTPUT_DIR: "./source/HomeBook.Client"
    CLIENT_NAMESPACE: "HomeBook.Client"
    CLIENT_CLASS: "BackendClient"
    UNIT_TEST_CSPROJ: "./source/HomeBook.UnitTests/HomeBook.UnitTests.csproj"
    PUBLISH_DIR: "./publish"
    FRONTEND_PUBLISH_DIR: "./publish/frontend"
    BACKEND_PUBLISH_DIR: "./publish/backend"
    WEBSITE_REPOSITORY: "homebook-app/homebook-app.github.io"
    WEBSITE_REPO_PATH: "./website-repo"
    WEBSITE_RELEASES_MARKDOWN_DIR: "app/content/releases"
    WEBSITE_RELEASES_JSON_FILE: "app/content/releases/releases.json"

jobs:

    build-test:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0
                    clean: true

            -   name: Set up JDK 17
                uses: actions/setup-java@v4
                with:
                    java-version: 17
                    distribution: "zulu"

            -   name: Setup .NET 10.0.101
                uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: ${{ env.DOTNET_VERSION }}

            -   name: Setup Node
                uses: actions/setup-node@v4
                with:
                    node-version: 22

            -   name: Install NPM Sass
                run: npm install --save-dev sass

            -   name: Install SonarQube Cloud scanner
                run: dotnet tool install --global dotnet-sonarscanner

            -   name: Install Kiota CLI
                run: dotnet tool install --global Microsoft.OpenApi.Kiota

            -   name: Install ReportGenerator
                run: dotnet tool install --global dotnet-reportgenerator-globaltool

            -   name: Install .NET Coverage
                run: dotnet tool install --global dotnet-coverage

            -   name: .NET Restore
                run: dotnet restore ${{ env.SOLUTION_FILE }}

            -   name: .NET Build (Service for Client Generation)
                run: dotnet build ${{ env.SOLUTION_FILE }} --no-restore

            -   name: Generate Client
                shell: bash
                run: |
                    kiota generate \
                      --language csharp \
                      --class-name ${{ env.CLIENT_CLASS }} \
                      --namespace-name ${{ env.CLIENT_NAMESPACE }} \
                      --openapi ${{ env.OPENAPI_FILE }} \
                      --output ${{ env.CLIENT_OUTPUT_DIR }}

            -   name: Begin SonarQube
                shell: pwsh
                env:
                    SONARTOKEN: ${{ secrets.SONAR_TOKEN }}
                run: |
                    dotnet-sonarscanner begin `
                      /k:"lk-code_homebook" `
                      /o:"lk-code-github" `
                      /d:sonar.token="$env:SONARTOKEN" `
                      /d:sonar.host.url="https://sonarcloud.io" `
                      /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml `
                      /d:sonar.exclusions="**/Licenses.json,**/Licenses/**,**/bin/**,**/obj/**,**/Migrations/**" `
                      /d:sonar.coverage.exclusions="**/Licenses.json,**/Licenses/**,**/bin/**,**/obj/**,**/Migrations/**" `
                      /d:sonar.cpd.exclusions="**/Licenses.json,**/Licenses/**,**/Migrations/**" `
                      /d:sonar.security.exclusions="**/Licenses.json,**/Licenses/**,**/Migrations/**"

            -   name: .NET Build
                shell: pwsh
                run: dotnet build ${{ env.SOLUTION_FILE }} --no-restore

            -   name: Collect Test Coverage
                shell: pwsh
                run: |
                    dotnet-coverage collect "dotnet test ${{ env.UNIT_TEST_CSPROJ }} --no-build" -f xml -o "coverage.xml"

            -   name: End SonarQube
                shell: pwsh
                env:
                    SONARTOKEN: ${{ secrets.SONAR_TOKEN }}
                run: |
                    dotnet-sonarscanner end /d:sonar.token="$env:SONARTOKEN"

            -   name: Publish frontend
                run: |
                    rm -rf ${{ env.PUBLISH_DIR }}
                    dotnet publish ${{ env.FRONTEND_CSPROJ }} --configuration Release --no-restore --output ${{ env.FRONTEND_PUBLISH_DIR }}

            -   name: Publish backend
                run: |
                    dotnet publish ${{ env.BACKEND_CSPROJ }} --configuration Release --no-restore --output ${{ env.BACKEND_PUBLISH_DIR }} /p:UseAppHost=false

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435

            -   name: Build Docker Image
                run: docker build --file ./Dockerfile --tag test-image .

    post-build:
        runs-on: ubuntu-latest
        needs:
            - build-test

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0
                    clean: true

            -   name: Configure Git User and Auth
                run: |
                    git config user.name "GitHub Actions"
                    git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                    git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

            -   name: Update Frontend appsettings.json
                run: |
                    sed -i "s/\"Version\": \".*\"/\"Version\": \"$VERSION\"/" ${{ env.FRONTEND_APPSETTINGS_FILE }}
                    git add ${{ env.FRONTEND_APPSETTINGS_FILE }}

            -   name: Update Backend appsettings.json
                run: |
                    sed -i "s/\"Version\": \".*\"/\"Version\": \"$VERSION\"/" ${{ env.BACKEND_APPSETTINGS_FILE }}
                    git add ${{ env.BACKEND_APPSETTINGS_FILE }}

            -   name: Create or update deploy branch
                run: |
                    git fetch origin
                    git checkout main
                    git pull origin main
                    git checkout -B deploy
                    if ! git diff --cached --quiet; then
                      git commit -m "Release version ${{ env.VERSION }}"
                    fi
                    git tag ${{ env.VERSION }}
                    git push origin deploy --force
                    git push origin ${{ env.VERSION }}

    client-deploy:
        runs-on: ubuntu-latest
        needs:
            - post-build

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
                with:
                    ref: deploy
                    clean: true

            -   name: Setup .NET 10.0.101
                uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: ${{ env.DOTNET_VERSION }}

            -   name: Install Kiota CLI
                run: dotnet tool install --global Microsoft.OpenApi.Kiota

            -   name: Restore dependencies
                run: dotnet restore ${{ env.SOLUTION_FILE }}

            -   name: Build Solution
                run: dotnet build ${{ env.SOLUTION_FILE }} --configuration Release --no-restore

            -   name: Generate Client
                run: |
                    kiota generate \
                      --language csharp \
                      --class-name ${{ env.CLIENT_CLASS }} \
                      --namespace-name ${{ env.CLIENT_NAMESPACE }} \
                      --openapi ${{ env.OPENAPI_FILE }} \
                      --output ${{ env.CLIENT_OUTPUT_DIR }}

            -   name: Build Client
                run: dotnet build ${{ env.CLIENT_CSPROJ }} --configuration Release --no-restore -p:PackageVersion=${{ env.VERSION }}

            -   name: Upload NuGet Artifact
                uses: actions/upload-artifact@v4.6.2
                with:
                    name: ${{ env.VERSION }}
                    path: "**/*.${{ env.VERSION }}.nupkg"

            -   name: Upload Client Artifact
                uses: actions/upload-artifact@v4.6.2
                with:
                    name: client-output
                    path: ${{ env.CLIENT_OUTPUT_DIR }}

            -   name: Publish
                run: dotnet nuget push "**/*.${{ env.VERSION }}.nupkg" --no-symbols --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }} --source "nuget.org"

    publish-artifacts:
        runs-on: ubuntu-latest
        needs:
            - post-build

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
                with:
                    ref: deploy
                    clean: true

            -   name: Setup .NET 10.0.101
                uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: ${{ env.DOTNET_VERSION }}

            -   name: Setup Node
                uses: actions/setup-node@v4
                with:
                    node-version: 22

            -   name: Install NPM Sass
                run: npm install --save-dev sass

            -   name: Restore dependencies
                run: dotnet restore ${{ env.SOLUTION_FILE }}

            -   name: Build Solution
                run: dotnet build ${{ env.SOLUTION_FILE }} --configuration Release --no-restore

            -   name: Publish frontend
                run: |
                    rm -rf ${{ env.PUBLISH_DIR }}
                    dotnet publish ${{ env.FRONTEND_CSPROJ }} --configuration Release --no-restore --output ${{ env.FRONTEND_PUBLISH_DIR }}

            -   name: Publish backend
                run: |
                    dotnet publish ${{ env.BACKEND_CSPROJ }} --configuration Release --no-restore --output ${{ env.BACKEND_PUBLISH_DIR }} /p:UseAppHost=false

            -   name: Upload publish artifacts
                uses: actions/upload-artifact@v4
                with:
                    name: publish-artifacts
                    path: ${{ env.PUBLISH_DIR }}

    docker-deploy:
        runs-on: ubuntu-latest
        needs:
            - publish-artifacts

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
                with:
                    ref: deploy
                    clean: true

            -   name: Download publish artifacts
                uses: actions/download-artifact@v4
                with:
                    name: publish-artifacts
                    path: ${{ env.PUBLISH_DIR }}

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435

            -   name: Log in to Docker Hub
                uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}

            -   name: Extract metadata (tags, labels) for Docker
                id: meta
                uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f
                with:
                    images: ${{ env.DOCKER_IMAGE }}
                    tags: |
                        type=raw,value=${{ env.VERSION }}
                        type=raw,value=latest

            -   name: Build and push Docker image
                uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
                with:
                    context: ./
                    file: ./Dockerfile
                    push: true
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}
                    platforms: ${{ env.DOCKER_PLATFORMS }}
                    cache-from: type=gha
                    cache-to: type=gha,mode=max

    website-release-sync:
        runs-on: ubuntu-latest
        needs:
            - docker-deploy

        steps:
            -   name: Git checkout
                uses: actions/checkout@v4
                with:
                    repository: ${{ env.WEBSITE_REPOSITORY }}
                    token: ${{ secrets.WEBSITE_GITHUBIO_REPO_TOKEN }}
                    path: ${{ env.WEBSITE_REPO_PATH }}
                    clean: true

            -   name: Configure Git User
                working-directory: ${{ env.WEBSITE_REPO_PATH }}
                run: |
                    git config user.name "GitHub Actions"
                    git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

            -   name: Create release markdown
                shell: bash
                run: |
                    set -euo pipefail

                    release_date="$(date -u +%Y%m%d)"
                    release_date_iso="$(date -u +%F)"
                    short_sha="${GITHUB_SHA:0:7}"
                    release_title="HomeBook ${VERSION}"
                    tag_url="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/tree/${VERSION}"
                    commit_url="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}"
                    run_url="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
                    markdown_file_name="${WEBSITE_RELEASES_MARKDOWN_DIR}/${release_date}-${VERSION}.md"
                    markdown_absolute_path="${WEBSITE_REPO_PATH}/${markdown_file_name}"

                    mkdir -p "$(dirname "$markdown_absolute_path")"

                    cat > "$markdown_absolute_path" <<EOF
                    # ${release_title}

                    - Date: ${release_date_iso}
                    - Version: ${VERSION}
                    - Commit: [\`${short_sha}\`](${commit_url})
                    - Workflow Run: [#${GITHUB_RUN_ID}](${run_url})

                    ## Artifacts

                    - Git tag: [\`${VERSION}\`](${tag_url})

                    ## Changes

                    * add here the changes of this release

                    EOF

            -   name: Add markdown path and release to json-file
                shell: bash
                run: |
                    set -euo pipefail

                    release_date="$(date -u +%Y%m%d)"
                    release_date_iso="$(date -u +%F)"
                    markdown_file_name="${release_date}-${VERSION}.md"
                    json_absolute_path="${WEBSITE_REPO_PATH}/${WEBSITE_RELEASES_JSON_FILE}"
                    short_sha="${GITHUB_SHA:0:7}"
                    commit_url="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}"
                    run_id="${GITHUB_RUN_ID}"

                    mkdir -p "$(dirname "$json_absolute_path")"

                    if [ ! -f "$json_absolute_path" ]; then
                      echo "[]" > "$json_absolute_path"
                    fi

                    entry_json="$(jq -n \
                      --arg version "$VERSION" \
                      --arg date "$release_date_iso" \
                      --arg markdownFile "$markdown_file_name" \
                      --arg short_sha "$short_sha" \
                      --arg commit_url "$commit_url" \
                      --arg run_id "$run_id" \
                      '{
                        version: $version,
                        date: $date,
                        markdownFile: $markdownFile,
                        short_sha: $short_sha,
                        commit_url: $commit_url,
                        run_id: $run_id
                      }')"

                    tmp_file="$(mktemp)"
                    jq --arg version "$VERSION" --argjson entry "$entry_json" '
                      (if type == "array" then . else [] end)
                      | map(select(.version != $version))
                      | [$entry] + .
                    ' "$json_absolute_path" > "$tmp_file"
                    mv "$tmp_file" "$json_absolute_path"

            -   name: Commit changes
                working-directory: ${{ env.WEBSITE_REPO_PATH }}
                run: |
                    if [ -z "$(git status --short)" ]; then
                      echo "No website release changes detected."
                      exit 0
                    fi

                    git add ${{ env.WEBSITE_RELEASES_MARKDOWN_DIR }} ${{ env.WEBSITE_RELEASES_JSON_FILE }}
                    git commit -m "Add release ${{ env.VERSION }}"
                    git push
