name: Deploy Docker Image to Docker Hub

on:
  #  push:
  #    branches:
  #      - deploy
  workflow_dispatch:

permissions:
  contents: write
  packages: write

env:
  DOCKER_IMAGE: "docker.io/lkcode/homebook"
  DOCKER_PLATFORMS: "linux/amd64,linux/arm64"
  VERSION: "1.0.${{ github.run_number }}"
  DOTNET_VERSION: "9.0.x"
  FRONTEND_APPSETTINGS_FILE: "./source/HomeBook.Frontend/wwwroot/appsettings.json"
  BACKEND_APPSETTINGS_FILE: "./source/HomeBook.Backend/appsettings.json"
  OPENAPI_FILE: "./source/HomeBook.Backend/HomeBook.Backend.json"
  CLIENT_CSPROJ: "./source/HomeBook.Client/HomeBook.Client.csproj"
  CLIENT_OUTPUT_DIR: "./source/HomeBook.Client"
  CLIENT_NAMESPACE: "HomeBook.Client"
  CLIENT_CLASS: "BackendClient"

jobs:

  docker-deploy:
    runs-on: ubuntu-latest
    needs:
      - post-build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: deploy

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: |
            type=raw,value=${{ env.VERSION }}
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.18.0
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ env.DOCKER_PLATFORMS }}
          build-args: |
            FRONTEND_APPSETTINGS_FILE=${{ env.FRONTEND_APPSETTINGS_FILE }}
            BACKEND_APPSETTINGS_FILE=${{ env.BACKEND_APPSETTINGS_FILE }}
