name: Pull Request

on:
    pull_request:
        branches: [ "main" ]

env:
    DOTNET_VERSION: "10.0.101"
    FRONTEND_APPSETTINGS_FILE: "./source/HomeBook.Frontend/wwwroot/appsettings.json"
    BACKEND_APPSETTINGS_FILE: "./source/HomeBook.Backend/appsettings.json"
    OPENAPI_FILE: "./source/HomeBook.Backend/HomeBook.Backend.json"
    CLIENT_CSPROJ: "./source/HomeBook.Client/HomeBook.Client.csproj"
    CLIENT_OUTPUT_DIR: "./source/HomeBook.Client"
    CLIENT_NAMESPACE: "HomeBook.Client"
    BACKEND_CSPROJ: "./source/HomeBook.Backend/HomeBook.Backend.csproj"
    FRONTEND_CSPROJ: "./source/HomeBook.Frontend/HomeBook.Frontend.csproj"
    UNIT_TEST_CSPROJ: "./source/HomeBook.UnitTests/HomeBook.UnitTests.csproj"
    E2E_TEST_CSPROJ: "./source/HomeBook.E2ETests/HomeBook.E2ETests.csproj"

jobs:
    pull-request-check:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   name: Set up JDK 17
                uses: actions/setup-java@v4
                with:
                    java-version: 17
                    distribution: 'zulu'

            -   name: Setup .NET
                uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: ${{ env.DOTNET_VERSION }}
                    global-json-file: ./global.json

            -   name: Setup Node
                uses: actions/setup-node@v4
                with:
                    node-version: 22

            -   name: Install NPM Sass
                run: npm install --save-dev sass

            -   name: Install SonarQube Cloud scanner
                run: dotnet tool install --global dotnet-sonarscanner

            -   name: Install Kiota CLI
                run: dotnet tool install --global Microsoft.OpenApi.Kiota

            -   name: Install ReportGenerator
                run: dotnet tool install --global dotnet-reportgenerator-globaltool

            -   name: Install .NET Coverage
                run: dotnet tool install --global dotnet-coverage

            -   name: Debug SDK
                run: |
                    pwd
                    dotnet --version
                    dotnet --info

            -   name: .NET Restore
                run: dotnet restore

            -   name: .NET Build (Service for Client Generation)
                run: dotnet build ${{ env.BACKEND_CSPROJ }} --no-restore

            -   name: Generate Kiota Client
                shell: bash
                run: |
                    kiota generate \
                      --language csharp \
                      --class-name RestClient \
                      --namespace-name ${{ env.CLIENT_NAMESPACE }} \
                      --openapi ${{ env.OPENAPI_FILE }} \
                      --output ${{ env.CLIENT_OUTPUT_DIR }}

            -   name: Skip SonarQube for Dependabot
                if: ${{ github.actor == 'dependabot[bot]' }}
                run: echo "Skipping SonarQube scan for Dependabot PR"

            -   name: Begin SonarQube
                if: ${{ github.actor != 'dependabot[bot]' }}
                shell: pwsh
                env:
                    SONARTOKEN: ${{ secrets.SONAR_TOKEN }}
                run: |
                    dotnet-sonarscanner begin `
                      /k:"lk-code_homebook" `
                      /o:"lk-code-github" `
                      /d:sonar.token="$env:SONARTOKEN" `
                      /d:sonar.host.url="https://sonarcloud.io" `
                      /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml `
                      /d:sonar.exclusions="**/Licenses.json,**/Licenses/**,**/bin/**,**/obj/**,**/Migrations/**" `
                      /d:sonar.coverage.exclusions="**/Licenses.json,**/Licenses/**,**/bin/**,**/obj/**,**/Migrations/**" `
                      /d:sonar.cpd.exclusions="**/Licenses.json,**/Licenses/**,**/Migrations/**" `
                      /d:sonar.security.exclusions="**/Licenses.json,**/Licenses/**,**/Migrations/**"

            -   name: .NET Build
                shell: pwsh
                run: dotnet build --no-restore

            -   name: Collect Test Coverage
                shell: pwsh
                run: |
                    dotnet-coverage collect "dotnet test ${{ env.UNIT_TEST_CSPROJ }} --no-build" -f xml -o "coverage.xml"

            -   name: End SonarQube
                if: ${{ github.actor != 'dependabot[bot]' }}
                shell: pwsh
                env:
                    SONARTOKEN: ${{ secrets.SONAR_TOKEN }}
                run: |
                    dotnet-sonarscanner end /d:sonar.token="$env:SONARTOKEN"

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435

            -   name: Build Docker Image
                run: |
                    docker build \
                      --file ./Dockerfile \
                      --build-arg FRONTEND_APPSETTINGS_FILE=${{ env.FRONTEND_APPSETTINGS_FILE }} \
                      --build-arg BACKEND_APPSETTINGS_FILE=${{ env.BACKEND_APPSETTINGS_FILE }} \
                      --tag test-image .

            -   uses: actions/upload-artifact@v4
                with:
                    name: coverage
                    path: coverage.xml
