<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <NeutralLanguage>en-US</NeutralLanguage>

        <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
        <StaticWebAssetsEnabled>true</StaticWebAssetsEnabled>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Humanizer" Version="3.0.10"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.5"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\HomeBook.Frontend.Core\HomeBook.Frontend.Core.csproj"/>
        <ProjectReference Include="..\HomeBook.Frontend.Abstractions\HomeBook.Frontend.Abstractions.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Resources\LocalizationStrings.resx">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>LocalizationStrings.resx</DependentUpon>
        </Compile>
    </ItemGroup>

</Project>
